//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace banxemayAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class xe
    {
        public string maxe { get; set; }
        public string tenxe { get; set; }
        public string mahang { get; set; }
        public string maloai { get; set; }
        public string mausac { get; set; }
        public string cannang { get; set; }
        public string docaoyen { get; set; }
        public string namsanxuat { get; set; }
        public string xuatxu { get; set; }
        public string dungtichbinhxang { get; set; }
        public string dungtichxilanh { get; set; }
        public Nullable<int> giaban { get; set; }
        [Newtonsoft.Json.JsonIgnore]
        [System.Xml.Serialization.XmlIgnore]
        public virtual hangxe hangxe { get; set; }
        public virtual loaixe loaixe { get; set; }
    }
}
